import dotenv from "dotenv";
import mongoose from "mongoose";
import { connectDatabase } from "../config/database.js";
import { Question } from "../models/Question.js";

dotenv.config();

const makeQuestion = (number, options, correctOptionId) => ({
  level: 1,
  type: "password",
  question: "Which is the strongest password?",
  options: options.map((text, index) => ({
    id: String.fromCharCode(65 + index),
    text,
  })),
  correctOptionId,
  explanation:
    "The strongest option is the most unpredictable and combines length with varied character types without relying on common personal or sequential patterns.",
  tip: "Use long, unique passwords or passphrases and never reuse them across accounts.",
  difficulty: "Intermediate",
  active: true,
  importKey: `L1-Q${String(number).padStart(2, "0")}`,
});

const questions = [
  makeQuestion(
    1,
    ["Password123", "Sangam@123", "Mango#47!Tree", "Welcome2026", "qwerty789"],
    "C",
  ),
  makeQuestion(
    2,
    ["India@123", "P@ssword2026", "Ravi2000!", "vK7#pL9@xQ2!", "Welcome@99"],
    "D",
  ),
  makeQuestion(
    3,
    ["Football@2026", "T!ger#82Moon$", "India12345", "Admin@123", "Cricket#1"],
    "B",
  ),
  makeQuestion(
    4,
    ["123456789", "P@ssW0rd!", "BlueSky2026", "N7$vQ2!mK8#r", "Password@123"],
    "D",
  ),
  makeQuestion(
    5,
    ["MyDog@2020", "Tr3e!Cloud#91", "Summer2026!", "qwerty@789", "Admin#2026"],
    "B",
  ),
  makeQuestion(
    6,
    [
      "Karnataka@123",
      "A7#pL2!xR9@z",
      "Bengaluru2026",
      "India@9876",
      "RVIM@123",
    ],
    "B",
  ),
  makeQuestion(
    7,
    [
      "ILovePizza123!",
      "9#vT2@kL7$xP",
      "Pizza@2026",
      "Foodie12345",
      "P@ssword!",
    ],
    "B",
  ),
  makeQuestion(
    8,
    [
      "Rahul@2001",
      "Cricket#2026",
      "X8!mQ4@zR7#kL",
      "Welcome@2026",
      "India#1234",
    ],
    "C",
  ),
  makeQuestion(
    9,
    [
      "MyPasswordIsStrong!",
      "H7@qL9#vX2!mR",
      "Password!2026",
      "StrongPassword123",
      "P@ssword1234",
    ],
    "B",
  ),
  makeQuestion(
    10,
    [
      "Summer#2026",
      "Z4!rT8@pQ2$xM",
      "SummerVacation2026!",
      "Welcome@2026!",
      "June2026@123",
    ],
    "B",
  ),
  makeQuestion(
    11,
    [
      "MyName@12345",
      "7#Kp!3xR@9Lm",
      "MyNameIsSangam!",
      "Sangam@2026",
      "Sangam12345",
    ],
    "B",
  ),
  makeQuestion(
    12,
    [
      "Qwerty@123456",
      "C0ffee#2026",
      "4$Nq8!Vz2@Lp",
      "Coffee12345",
      "Admin@987654",
    ],
    "C",
  ),
  makeQuestion(
    13,
    [
      "Blue#Sky#Cloud#123",
      "B7@xQ2!mL9#rT",
      "BlueSky2026!",
      "Sky123456789",
      "Cloud@2026",
    ],
    "B",
  ),
  makeQuestion(
    14,
    [
      "January2026!",
      "J@nuary#2026",
      "9v!Q2@Lm7#Xr5",
      "Winter@123",
      "NewYear2026",
    ],
    "C",
  ),
  makeQuestion(
    15,
    [
      "1234!@#$5678",
      "A1!b2@C3#d4$",
      "Password!@#$",
      "Qwerty123!@",
      "1111AAAA!!!!",
    ],
    "B",
  ),
  makeQuestion(
    16,
    [
      "correcthorsebatterystaple",
      "C0rrect!Horse#91",
      "HorseBatteryStaple123",
      "horse123456789",
      "CorrectHorse!",
    ],
    "B",
  ),
  makeQuestion(
    17,
    [
      "P@sswordP@ssword123",
      "K8!vR2@pL7#xQ4",
      "PasswordPassword!",
      "Pass123Pass123",
      "WelcomeWelcome@1",
    ],
    "B",
  ),
  makeQuestion(
    18,
    [
      "S0mething!Random#47",
      "SomethingRandom2026",
      "Random@123456",
      "RandomPassword!",
      "Random12345",
    ],
    "A",
  ),
  makeQuestion(
    19,
    [
      "Myschool@2026",
      "9$kL!2vQ@7Xp#R",
      "SchoolName123!",
      "Student@2026",
      "College123456",
    ],
    "B",
  ),
  makeQuestion(
    20,
    [
      "December@2026",
      "WinterWinter123!",
      "T6#pQ9!xL2@vM",
      "Christmas2026!",
      "NewYear@123",
    ],
    "C",
  ),
  makeQuestion(
    21,
    [
      "Sangamesh@123",
      "Bengaluru#2026",
      "V8!qL3@xP7#nR2",
      "RVIM2026!",
      "MBA@2026",
    ],
    "C",
  ),
  makeQuestion(
    22,
    [
      "Abc@123456789",
      "Q7#mP2!vL9@xR",
      "Aaaaa11111!",
      "Welcome123456!",
      "Password20262026",
    ],
    "B",
  ),
  makeQuestion(
    23,
    [
      "Th1sIsMyP@ssword!",
      "F9@kL2#qX7!vM",
      "ThisIsMyPassword2026",
      "MyPassword!12345",
      "P@sswordIsMine2026",
    ],
    "B",
  ),
  makeQuestion(
    24,
    [
      "R@ndomP@ss123456",
      "X4!qN8@vL2#pR7$",
      "MySecurePassword!2026",
      "Secure123456789!",
      "P@ssw0rdSecure2026",
    ],
    "B",
  ),
  makeQuestion(
    25,
    [
      "MyFavouriteMovie@2026",
      "M0v!e#Tiger@47Cloud",
      "MovieMovie123456!",
      "FavouriteMovie@123",
      "Tiger@2026Movie",
    ],
    "B",
  ),
  makeQuestion(
    26,
    [
      "Summer!Rain#Cloud92",
      "Tr0ub4dor&3",
      "Purple7!Window$Chair",
      "vQ8#tL2@zR9!mX4",
      "MyDog!Runs@Fast2026",
    ],
    "D",
  ),
  makeQuestion(
    27,
    [
      "C0ffee!C0ffee!C0ffee!",
      "f7@Kq2!Lm9#Xr5",
      "Correct-Horse-Battery-Staple",
      "Monday@Tuesday#Wednesday",
      "P@ssw0rd!Secure#2026",
    ],
    "B",
  ),
  makeQuestion(
    28,
    [
      "Giraffe!72-Blue-Window",
      "9x!Qp7#Lm2@Vr8",
      "Football!Football!92",
      "Winter$Summer#Spring@Fall",
      "Admin@45!SecurePassword",
    ],
    "B",
  ),
  makeQuestion(
    29,
    [
      "A7!A7!A7!A7!A7!",
      "Blue-Moon-Blue-Moon-47",
      "kR8@vN3!qL7#xP2",
      "Password!Password!Password!",
      "Rocket#Moon@Star123456",
    ],
    "C",
  ),
  makeQuestion(
    30,
    [
      "HorseBatteryStaple!92",
      "z8#Lm2@Qv7!Rx4$",
      "SummerVacation!Summer2026",
      "Qwerty!Asdf#Zxcv",
      "Coffee@Morning#Coffee",
    ],
    "B",
  ),
  makeQuestion(
    31,
    [
      "T!ger#82Moon$47",
      "7m@Q2#vL9!xR5",
      "MyFavouriteBook!1989",
      "Secure@Secure#Secure123",
      "RedBlueGreenYellow!",
    ],
    "B",
  ),
  makeQuestion(
    32,
    [
      "P@ssword123!P@ssword",
      "q8#Vt2!Lm7@Rx9",
      "Sunshine!Rain!Cloud!",
      "January@February#March",
      "MySecretPassword!47",
    ],
    "B",
  ),
  makeQuestion(
    33,
    [
      "N3ptune!Glass#River72",
      "8q@L2!xR7#Vm5",
      "NeptuneNeptune123!",
      "Glass@River#72Neptune",
      "Password!River#72",
    ],
    "B",
  ),
  makeQuestion(
    34,
    [
      "F!reWall#Blue72",
      "x7@Pq3!Lm8#Vr2",
      "FirewallFirewall2026!",
      "BlueFire@Wall#2026",
      "F1rewall!Secure123",
    ],
    "B",
  ),
  makeQuestion(
    35,
    [
      "3x!Lm8@Qv2#Rt7",
      "MyPasswordIsVeryStrong!",
      "VeryStrongPassword123!",
      "Strong!Password#Strong",
      "P@ssword123456789!",
    ],
    "A",
  ),
  makeQuestion(
    36,
    [
      "GreenTea!Morning#42",
      "G7@kP2!xL9#Vm4",
      "TeaCoffeeJuice@123",
      "Morning#42Morning#42",
      "GreenTeaGreenTea!",
    ],
    "B",
  ),
  makeQuestion(
    37,
    [
      "9v#Qm2!Lx7@Rp5",
      "Welcome!Welcome!2026",
      "December@31#January1",
      "P@ssword!123456789",
      "SecureLogin#SecureLogin",
    ],
    "A",
  ),
  makeQuestion(
    38,
    [
      "M0on!Light#River82",
      "MoonLightMoonLight123",
      "Moon@Light#River2026",
      "M00n!L1ght!2026",
      "x4@Nq8#Lv2!Rp7",
    ],
    "E",
  ),
  makeQuestion(
    39,
    [
      "Qwerty!123456789",
      "q7#Lm2@Xr9!Vp4",
      "Keyboard@2026!Secure",
      "Qw3rty!Keyboard#92",
      "Asdfgh@123456!",
    ],
    "B",
  ),
  makeQuestion(
    40,
    [
      "BlueSky!BlueSky!72",
      "B7!xQ3@Lm8#Vr5",
      "SkyBlueCloud@12345",
      "Blue#Sky#Cloud#River",
      "CloudRiverSky!2026",
    ],
    "B",
  ),
  makeQuestion(
    41,
    [
      "Password!@#$123456",
      "P@55w0rd!Secure#92",
      "8r#Qm5!Vx2@Lp9",
      "SecurePassword!Secure",
      "P@ssword123456789!",
    ],
    "C",
  ),
  makeQuestion(
    42,
    [
      "Coffee!Tea#Juice@Milk",
      "CoffeeCoffeeCoffee!92",
      "C0ffee!T3a#Juice72",
      "7x@Lq2#Vp9!Rm5",
      "MorningCoffee@123456",
    ],
    "D",
  ),
  makeQuestion(
    43,
    [
      "Red7!Blue8@Green9#",
      "R3d!Blu3@Gr33n#2026",
      "RedBlueGreen123!",
      "7p#Xq2!Lm8@Vr4",
      "Red@Blue#Green$Yellow",
    ],
    "D",
  ),
  makeQuestion(
    44,
    [
      "Summer2026!Winter2027",
      "s8@Qm3!Lx7#Vr2",
      "Summer!Winter!Spring!",
      "S0mmer!W1nter#2026",
      "WinterSummer123456",
    ],
    "B",
  ),
  makeQuestion(
    45,
    [
      "A1!B2@C3#D4$E5%",
      "x9@Lm3!Qv7#Rp2",
      "12345!@#$%67890",
      "Aa1!Aa1!Aa1!Aa1!",
      "Password@1Password@2",
    ],
    "B",
  ),
  makeQuestion(
    46,
    [
      "L0ngPassword!ButPredictable",
      "7q#Vm2@Lp8!Rx5",
      "CorrectHorseBatteryStaple!",
      "ThisIsMyVeryStrongPassword!",
      "MyPasswordHasManyCharacters123!",
    ],
    "B",
  ),
  makeQuestion(
    47,
    [
      "x4#Qp8!Lm2@Vr7",
      "Admin!@#Admin!@#",
      "Administrator@2026!",
      "Adm1n!Secure#2026",
      "AdminPassword!12345",
    ],
    "A",
  ),
  makeQuestion(
    48,
    [
      "R4nd0m!P@ssw0rd#92",
      "8m@Qx3!Lp7#Vr5",
      "RandomPassword!Random",
      "P@ssword!Random123",
      "Random!Random!Random!",
    ],
    "B",
  ),
  makeQuestion(
    49,
    [
      "NeverGuessThisPassword!",
      "N3v3r!Gu3ss#Th1s92",
      "9x#Qm7!Lp2@Vr8",
      "GuessMeNot!123456",
      "PasswordNobodyKnows!",
    ],
    "C",
  ),
  makeQuestion(
    50,
    [
      "Blue!72-River#Moon",
      "B7@xL2!Qm9#Vr4",
      "BlueRiverMoon!Blue",
      "BlueRiver@72#Moon",
      "RiverMoonBlue123!",
    ],
    "B",
  ),
];

const run = async () => {
  const connected = await connectDatabase();
  if (!connected)
    throw new Error("MongoDB is not connected. Configure backend/.env first.");

  await Question.deleteMany({ level: 1 });
  await Question.insertMany(questions);
  console.log(`Seeded ${questions.length} Level 1 questions.`);
  await mongoose.disconnect();
};

run().catch(async (error) => {
  console.error(error.message);
  await mongoose.disconnect();
  process.exitCode = 1;
});
